#!/usr/bin/env bash
read x
read y
read z
if (((( $x == $y )) & (( $y == $x )))); 
	then echo "EQUILATERAL";
		elif (( $y == $z )) && (( $z != $x ));
			then echo "ISOSCLESE";
        elif (( $x == $y )) && (( $z != $y ));
            then echo "ISOSCELSE";
	else echo "SCALENE";
fi;
